'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Dmt_tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AttachmentDetails.
        '''</summary>
        Friend ReadOnly Property AttachmentDetailsProperty() As String
            Get
                Return ResourceManager.GetString("AttachmentDetailsProperty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to e7f970b8-9bd1-4855-9fe1-7abb2f5279c1.
        '''</summary>
        Friend ReadOnly Property CoCdGUID() As String
            Get
                Return ResourceManager.GetString("CoCdGUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://eu001-sp.shell.com/sites/AAAAA4854/GlobalProjects/TMToolkit/myRTV/Global-RTV-Repository.
        '''</summary>
        Friend ReadOnly Property DmtServerName() As String
            Get
                Return ResourceManager.GetString("DmtServerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 57e39fdf-5528-4f5c-9fc2-d1b0eaf461ae.
        '''</summary>
        Friend ReadOnly Property EntitiesGUID() As String
            Get
                Return ResourceManager.GetString("EntitiesGUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d6afd335-761f-4a95-b4cc-3830cfdf579a.
        '''</summary>
        Friend ReadOnly Property HelpersGUID() As String
            Get
                Return ResourceManager.GetString("HelpersGUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&apos;Krk&apos;: {&apos;DmtServerName&apos;: &apos;https://eu001-sp.shell.com/sites/AAAAA4854/GlobalProjects/TMToolkit/myRTV/Global-RTV-Repository&apos;,&apos;CoCdGUID&apos;: &apos;e7f970b8-9bd1-4855-9fe1-7abb2f5279c1&apos;,&apos;ToolVersionGUID&apos;: &apos;e3af78c1-8624-42ee-b0af-38f7b0e6198d&apos;,&apos;EntitiesGUID&apos;: &apos;57e39fdf-5528-4f5c-9fc2-d1b0eaf461ae&apos;,&apos;HelpersGUID&apos;: &apos;d6afd335-761f-4a95-b4cc-3830cfdf579a&apos;,&apos;TrackingGUID&apos;: &apos;64ADA00E-56E7-4F99-AD63-19EE545DC97E&apos;},&apos;Rpa&apos;: {&apos;DmtServerName&apos;: &apos;https://eu001-sp.shell.com/sites/AAAAA4854/GlobalProjects&apos;,&apos;CoCdGUID&apos;: &apos;e7f970b8&apos;,&apos;ToolV [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jsonConnections() As String
            Get
                Return ResourceManager.GetString("jsonConnections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Apps\DTRTemp\.
        '''</summary>
        Friend ReadOnly Property temporaryFolderPath() As String
            Get
                Return ResourceManager.GetString("temporaryFolderPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 64ADA00E-56E7-4F99-AD63-19EE545DC97E.
        '''</summary>
        Friend ReadOnly Property TrackingGUID() As String
            Get
                Return ResourceManager.GetString("TrackingGUID", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
